version: '3.8'

services:
  app:
    build: .
    restart: always
    environment:
      - MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/rezium-bot?retryWrites=true&w=majority
      - PORT=3000
    ports:
      - "3000:3000"